apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: "Prometheus"
      type: prometheus
      uid: prometheus
      url: http://prometheus-stack-kube-prom-prometheus.monitoring:9090/
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
    - name: "Alertmanager"
      type: alertmanager
      uid: alertmanager
      url: http://prometheus-stack-kube-prom-alertmanager.monitoring:9093/
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: prometheus
    - name: "Loki"
      type: loki
      uid: loki
      url: http://loki-stack.monitoring.svc.cluster.local:3100/loki
      access: proxy
      isDefault: false
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-stack
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-10-10T18:39:09Z"
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 78.0.0
    chart: kube-prometheus-stack-78.0.0
    grafana_datasource: "1"
    heritage: Helm
    release: prometheus-stack
  name: prometheus-stack-kube-prom-grafana-datasource
  namespace: monitoring
  resourceVersion: "53104"
  uid: 3b3f0acc-3b49-47a3-b82f-85b3ef836828
