apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubelet-cadvisor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      k8s-app: kubelet
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: http-metrics
      path: /metrics/cadvisor
      interval: 30s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
