apiVersion: v1
kind: LimitRange
metadata:
  name: sandbox-limits
  namespace: test-sandbox
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sandbox-quota
  namespace: test-sandbox
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
